### PR TITLE
Adding basic unit tests

### PR DESCRIPTION
**Pull request by hokeun**

### CODE REVIEW

**Comment by chanijjani** [comment]
Related to https://github.com/hokeun/lf-rust-rti/issues/13.

Suggestion: How about completing unit tests of sources (federate_info.rs / lib.rs / net_common.rs / rti_remote.rs / tag.rs) in this PR?

**Comment by hokeun** [comment]
> It is related to #13.
> 
> **Suggestion:** How about completing easier unit tests of sources (federate_info.rs / lib.rs / net_common.rs / rti_remote.rs / tag.rs) in this PR?

Sounds good to me! Let's merge this PR cnce we're done with these .rs files,

**Comment by chanijjani** [comment]
image

**Comment by chanijjani** [comment]
@the-systematic-chaos Are you implementing and uploading the remaining unit test cases (TCs) of tag.rs within a few days? Before I add commits for unit TCs of sources from up-to-down directions in [the above code coverage graph](https://github.com/hokeun/lf-rust-rti/pull/24#issuecomment-1922290319) soon, I'll wait for you to finish your first commit.

**Comment by the-systematic-chaos** [comment]
@chanijjani 

Hi Dr. Lee, yes I think I will be able to get it done in a few days. I am progressing with the test cases.

**Comment by chanijjani** [comment]
image
[code_coverage_20240208.zip](https://github.com/hokeun/lf-rust-rti/files/14217467/code_coverage_20240208.zip)

**Comment by chanijjani** [comment]
image

**Comment by chanijjani** [comment]
It is necessary to rebase the main branch to enable CI After https://github.com/hokeun/lf-rust-rti/pull/42.

**Review by chanijjani — APPROVED** [review]
LGTM! We'd better make another PR for the remaining unit TC implementation.

**Pull request merged**
